### ISSUE TITLE
dkim header

### ISSUE THREAD

**Issue by VVhiteCoder** [astzweig/docker-wildduck#13]
can not figure out how to pass dkim signature header
`signTransportDomain=true` in `/etc/nodemailer/wildduck/dkim.toml`

still, nothing about dkim in sent messages header, should be some additional configuration or it's a kind of bug?

**Comment by rqelibari** [comment]
Hi @VVhiteCoder,

Can you please describe what you have tried so far?
To configure DKIM you need to do the following steps:

1. You need to mount the configuration files to your docker host computer. If you used the provided [docker-compose.yml](https://github.com/astzweig/docker-wildduck/blob/master/docker-compose.yml#L17) your configuration files are inside the docker `mailconfig` volume.

2. You need to set the `signTransportDomain` key to `true` in the `/etc/nodemailer/wildduck/dkim.toml` file.

3. You need to generate a DKIM key for the domain using the following command on your docker host computer:

```bash
$ docker-compose exec mail generate_dkim
```

The command will ask you for the domain name the key shall be assigned to and will add that key to the database. The command can be run multiple times as it will do nothing if a domain already has a key set.

For your information: You can use the wildduck API to find out, if there is already a DKIM key set for a domain.

Let me know if that solves your issue.

**Comment by VVhiteCoder** [comment]
@rqelibari 
this is my docker-compose.yml :
```
version: "3.5"
#https://github.com/astzweig/docker-wildduck
services:
    wildduck_mail:
        container_name: wildduck_mail
        image: astzweig/wildduck
        ports:
            - "25:25"
            - "465:465"
            - "993:993"
            #- "5438:443"
        networks:
            - wildduck
            - wildduck_ext
        volumes:
            - /web/nginx_proxy_manager/letsencrypt/live/npm-1/fullchain.pem:/etc/tls-keys/pub.pem:ro
            - /web/nginx_proxy_manager/letsencrypt/live/npm-1/privkey.pem:/etc/tls-keys/prv.pem:ro
            - wildduck_mailconfig:/etc/nodemailer
        links:
            - wildduck_redis:redis
            - wildduck_mongo:mongo
        environment:
            - FQDN=mail1.mydomain.com
            - MAIL_DOMAIN=mail1.mydomain.com
            - PRODUCT_NAME=MyDomain
            - TLS_KEY=/etc/tls-keys/prv.pem      # If you want to activate SSL for the mail services
            - TLS_CERT=/etc/tls-keys/pub.pem    # you will need to provide these two variables.
            - API_ENABLE=true
            - API_USE_HTTPS=true
            - API_URL=https://mail1.mydomain.com
            - API_TOKEN_SECRET=.....
            - GRAYLOG_HOST_PORT=https://graylog.mydomain.com/__gelf/mail
            - IMAP_PROCESSES=6
            - IMAP_RETENTION=30
            - ENABLE_SMTP_SEND_LATER=true
    wildduck_redis:
        container_name: wildduck_redis
        image: redis:alpine
        volumes:
            - wildduck_redis:/data
        networks:
            - wildduck
    
    wildduck_mongo:
        container_name: wildduck_mongo
        image: mongo
        volumes:
            - wildduck_mongo:/data/db
        networks:
            - wildduck

networks:
  wildduck:
    name: wildduck
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/28
  wildduck_ext:
    name: wildduck_ext
    external:
      name: nginx_proxy_manager
    
volumes:
  wildduck_mailconfig:
    name: wildduck_mailconfig
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /web/wildduck/mailconfig
  wildduck_redis:
    name: wildduck_redis
    driver: local    
    driver_opts:
      o: bind
      type: none
      device: /web/wildduck/redis
  wildduck_mongo:
    name: wildduck_mongo
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /web/wildduck/mongo
```

API request of dkim signature:

```
GET https://mail1.mydomain.com/dkim/123412312312312
X-Access-Token: {{token}}
content-type: application/json

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 07 Apr 2020 13:02:42 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Content-Encoding: gzip
X-Served-By: mail1.mydomain.com

{
  "id": "123412312312312",
  "domain": "mail1.mydomain.com",
  "selector": "mar2020",
  "description": "Default DKIM key for mail1.mydomain.com",
  "fingerprint": "<fingerprint>",
  "publicKey": "<public key>",
  "dnsTxt": {
    "name": "mar2020._domainkey.mail1.mydomain.com",
    "value": "v=DKIM1;t=s;p=<hash>"
  },
  "created": "2020-04-03T17:20:12.611Z",
  "success": true
}
```
dns txt record:

```
mar2020._domainkey.mail1.mydomain.com     TXT       v=DKIM1;t=s;p=<hash>
```

dkim.toml :
```
/ # cat /etc/nodemailer/wildduck/dkim.toml 
# If enabled then encrypt DKIM keys with the secret password. By default DKIM keys
# are not encrypted and stored as cleartext. Once set up do not change these values,
# otherwise decrypting DKIM keys is going to fail
#cipher="aes192"
#secret="a secret cat"

# If true then spwans openssl command line executable for generating DKIM keys
# Otherwise forge library is used which is cross-environment but slower
useOpenSSL=true
# Define path to openssl if not in default path
#pathOpenSSL="/usr/local/bin/openssl"

# If true then also adds a signature for the outbound domain
# Affects WildDuck ZoneMTA plugin only
signTransportDomain=true

# do not change this
hashAlgo="sha256"
/ # 
```

header of the email sent from mailspring client using wildduck to gmail (without dkim header - the actual problem):

```
Delivered-To: some@gmail.com
Received: by 2002:a05:6214:586:0:0:0:0 with SMTP id am275whsm3zdgpgrw7mc;
        Tue, 7 Apr 2020 08:41:00 -0700 (PDT)
X-Google-Smtp-Source: APiQypKTJaGoQSyqohwzS1M8416zh+3fdRTER345HDFsfiaoaGKtujeJW6rOd/L6+3izrFsa/
X-Received: by 2002:a7b:c402:: with SMTP id aaaaaaaaaaa.21.1111111111;
        Tue, 07 Apr 2020 08:40:59 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=111111111; cv=none;
        d=google.com; s=arc-111111111;
        b=Bwd9DMSZi45kLuXwp/KY0rqhI7Kx+fnJAIezy+a3ULFC1onQ/7vivTjZic7GLQi4Qo
         Mx4FcYUONg/SDFSDFFJGJFGHDFUUFDGDFDCFGLEE7A2fq9Z8GXBy+W3kyPv++BziaepM
         fCciEKHfU8Wxd10rGl1Q/Ot0gN7up0KOFvpkJHuXs4r+TmUWulKx8KUyTVOqPKdOKhQ1
         ut3FlobHK34jKXNBllVL6TVpEWTRIYUTYKMDCVBDSDHYK2PdRsx4H5W4CBQrnit3Fl0T
         XoziCWbOprpAJ0YidVssdWVwkB1qeOUwPmUQ9P9UpyG5Kg7bYO7prkv/311HFYq20HiW
         rBVQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-111111111;
        h=mime-version:subject:message-id:to:from:date;
        bh=aAPxsQgfbQcFxGh1+YCEtwert33EWQYjQhiFLjuRGQ=;
        b=wrRpXQvfzPCaJKILTUYIRUYTGSDVXVCNKTYUKFGFHSDBXCBMnhoP1KDi8zxpJaBJbqb
         PUJUGDNtQ2npkiUktgh3dAAeM8kFiaBnl4D4ee3w+qVfkEpXAw84rNU+BLUkXv/vOzZf
         6s2yOhph4FbdVM5WQETERTYITYKMNVS245DFGHDGJJGHDDXNVP5mCJAoCmEaZotQ4Cgt
         zRlZeUJDBMsBPbvKQi+wZuqHxAJriBb2ArVIYnqX1vm2zuvMdb32ef+6A/e5EXLb3eUL
         lIIJGFwUEYwXJhQC4kTw54jlQXcu1TiebF+2cDbz1SI7807feS2VD0UijAzWhml8eamM
         l3Qg==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of any@mydomain.com designates 2.2.2.2 as permitted sender) smtp.mailfrom=any@mydomain.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=mydomain.com
Return-Path: <john@mydomain.com>
Received: from mail1.mydomain.com (mail1.mydomain.com. [2.2.2.2])
        by mx.google.com with ESMTPS id o2erwr2336419wmh.200.2020.04.07.08.40.59
        for <some@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Tue, 07 Apr 2020 08:40:59 -0700 (PDT)
Received-SPF: pass (google.com: domain of john@mydomain.com designates 2.2.2.2 as permitted sender) client-ip=2.2.2.2;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of john@mydomain.com designates 2.2.2.2 as permitted sender) smtp.mailfrom=john@mydomain.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=mydomain.com
Received: from durdom-nout ([1.1.1.1] 1.1.1.1.starlink.com) (Authenticated sender: svvitch[svvitch]) by mail1.mydomain.com (ZoneMTA) with ESMTPSA id 171554d35b3a75.001 for <some@gmail.com> (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256); Tue, 07 Apr 2020 15:40:55 +0000
X-Zone-Loop: a4225560ebldkfjweiroio34klf148acedda2a539f45051ae07
X-Originating-IP: [1.1.1.1]
Date: Tue, 7 Apr 2020 18:40:54 +0300
From: john Wisent <john@mydomain.com>
To: "some@gmail.com" <some@gmail.com>
Message-ID: <B4668FF2-B731-4352-BCAF-AFERTWERBC18E@getmailspring.com>
Subject: testing dkim header
X-Mailer: Mailspring
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="5e232er_28f6f369_b0c"

```

header of the email sent from mailspring client using gmail to gmail  (with dkim header):

```
Delivered-To: some@gmail.com
Received: by 2001:a05:6214:586:0:0:0:0 with SMTP id bx6csp1057556qvb;
        Tue, 7 Apr 2020 08:53:56 -0700 (PDT)
X-Received: by 2001:a5d:4ecf:: with SMTP id s15mr432078wrv.190.1582274836614;
        Tue, 07 Apr 2020 08:53:56 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1582374836; cv=none;
        d=google.com; s=arc-20111816;
        b=c+fwzVLSW12b2Fr67gGu6VDNt5/m52rt7yeyrptfrqqapcfAlO5Zo4CyJSla1MxWlWr
         /uqy9uYRDt41pZ/bzwzbu7hiUWE8AN5UdkTPH3sGTXhZutT2kfHlIo4dwLYky7H6omgK
         o5U0Za/9reuXVB/sR6sJopnVnZol/mw29dnWnA9rks86LW5lojQapuIHG/56AXTEJLBk
         o4sMoJWkm2n3ie0rmnmblNuI0+mjuWFjXYORlICjdtT44hVPhHfnc/N0rnHqDBTszbiP
         FWymvuMS9xghg24FaUnrRx4gRm698SWIrHq/r8NNRlwu0sPDD8uO2gAIxHp6ujTPR8RS
         T2iA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20100016;
        h=mime-version:subject:message-id:to:from:date:dkim-signature;
        bh=CKNNg2wQIv50UrxQZ/8r466vcds6gp5mp9sj3rcrpjx99a4v66fvv7ft45f=;
        b=ppSPfdID2aO+PD8zv8Fylvrqy4zx65rnaaej8hGG373HRIJAIeLZW4mMotUpniM2gj5
         Jlt6/sleAy7He03VKI2GW69HQqV/WXAVTKVtN8wddfjeBEXPeN8Py/DkBfUpPZQ1GDoA
         4Jl+CCNwh0HXFbzSo9HoMmPxqbAL1XU2LTl1XW5tll4j47uPIzj99qKjKTZIa2vv4Nn/
         cvbm8hPG4RIImvoyTPej0gLgXNquckuJLtyTKH7YBeFP09PkLh4tvJ9wkiMnP66dzP4r
         lLIyloUOuhB3MQzh2Ef1zxbUID2Lg3K5R/aMPSCKhcbPQhQNH8iXxFdfpUE2Qyl56fn9
         kSPQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@gmail.com header.s=20161025 header.b=AYVzXReh;
       spf=pass (google.com: domain of john@gmail.com designates 2.2.2.2 as permitted sender) smtp.mailfrom=john@gmail.com;
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com
Return-Path: <john@gmail.com>
Received: from mail-sor-f41.google.com (mail-sor-f41.google.com. [2.2.2.2])
        by mx.google.com with SMTPS id i3sor1363476wra.61.2020.04.07.08.53.56
        for <some@gmail.com>
        (Google Transport Security);
        Tue, 07 Apr 2020 08:53:56 -0700 (PDT)
Received-SPF: pass (google.com: domain of john@gmail.com designates 2.2.2.2 as permitted sender) client-ip=2.2.2.2;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@gmail.com header.s=20161025 header.b=AYVzXReh;
       spf=pass (google.com: domain of john@gmail.com designates 2.2.2.2 as permitted sender) smtp.mailfrom=john@gmail.com;
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20160225;
        h=date:from:to:message-id:subject:mime-version;
        bh=CKNNg2wQIv50UrxQZ/8r466vcds6gp5mp9sj3rcrpjx99a4v66fvv7ft45f=;
        b=AYVzXRehwPCp5tcDbHXFlnHDrc6bKTmOErxI7OhUTC/XEBNMuNpgHfzDEIVMfgnN/V
         WdDK3s6xoFlHNsuQLZfTaUDc/w9FmhhMDT/WTyjeh4QAXtKNnH2AeR5L8DJpD4/XCfMX
         YvU8WBIuVyvEwq7riqIKRx6Ogm4aTVogO996d7I/KH0wKGbmV4iNSr+6LthHlLfO3IVl
         JSzVpCLOAHAuSuQlm1naTLUOH/VA8J5jNFAlVIWMa6iLecgjP1LucJtoUoX2m9OT4Bsr
         H6PsslXvP1sZ3WOYY9C34PxX010ScHfDPvOw4NtzRkw+j7g5tGUL8yXhrLzDARRyIIZx
         OE+g==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20231025;
        h=x-gm-message-state:date:from:to:message-id:subject:mime-version;
        bh=CKNNg2wQIv50UrxQZ/8r466vcds6gp5mp9sj3rcrpjx99a4v66fvv7ft45f=;
        b=kEIxN0P7JObQouDzwGKU/gprPcOLSJCH4DSDkZqbWThKer2COQt1utXRax7QFsl/ZA
         LlZqanisna7G40NR4ZwJE0U+IyMLHl6wMwlf4Lv2ddSDaJ/glwAaHK+Rc9+09dAWJ+2A
         wfYzR3EMjNRErssqR1YB+IyzVn2JLkh4A2CqCgH/3GKVGPjwiQ4+1mDeDtuQSwJSHqMw
         Kyuq/NNJXZCyi5H7SmmpFXGXrG8pRMyzgROw/W82Xi415BePUOxzUJ8nJOuGmBBxSq+g
         3x06g7/043jxMgGTyz60cAAezezw58v4zJ+K1zvMDbC08tlajLE6k2r8P3yrnj4WLQbZ
         afEg==
X-Gm-Message-State: AGi0PuYs1XpWuTnr6mE3BNVpy8ZjkZy9WBw92dBHg6THL54+ZdOalDn3Bgrp VOjk4ELWXynw6prE+gHJVXG6Plwz0xk=
X-Google-Smtp-Source: APiQypLluY9/3qYq6ChHtSyvrfRhZJP3ntbbaQSyp3wywr7c9xg7+keyju8XXHj0/+vBKJVD8LnaPnATobdA==john
X-Received: by 2002:adf:db42:: with SMTP id f2mr3653889wrj.226.1586274836137;
        Tue, 07 Apr 2020 08:53:56 -0700 (PDT)
Return-Path: <john@gmail.com>
Received: from durdom-nout ([1.1.1.1])
        by smtp.gmail.com with ESMTPSA id x5sm2333645wmk.29.2021.04.07.08.53.55
        for <some@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 07 Apr 2020 08:53:55 -0700 (PDT)
Date: Tue, 7 Apr 2020 18:53:54 +0300
From: John Snow <john@gmail.com>
To: "some@gmail.com" <some@gmail.com>
Message-ID: <157C9FB2-7B7E-4CA9-8333-234243DFSSFA862@getmailspring.com>
Subject: testing dkim from mailspring
X-Mailer: Mailspring
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="5e8ca212_4217c4f5_3821"
```

problem: I'm trying to set the DKIM-Signature in message header,
thank you @rqelibari if you have any idea I'm ready to investigate
